/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;

/**
 *
 * @author ronald
 */
public class PanelBotonesAccion extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotonesAccion
     */
    public PanelBotonesAccion() {
        initComponents();
        init();
    }
    
    public void init(){
      jbAceptar.setActionCommand(PanelBotonesAccion.BOTON_ACEPTAR);
      jbCancelar.setActionCommand(PanelBotonesAccion.BOTON_CANCELAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        jbAceptar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbAceptar.setText("Aceptar");

        jbCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancelar)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbAceptar)
                .addComponent(jbCancelar))
        );
    }// </editor-fold>//GEN-END:initComponents

public void setControlador(ActionListener controlador){
    jbAceptar.addActionListener(controlador);
    jbCancelar.addActionListener(controlador);
}
    public static final String BOTON_ACEPTAR="Aceptar";
    public static final String BOTON_CANCELAR="Cancelar";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    // End of variables declaration//GEN-END:variables
}
